language: go
sudo: false
go:
  - 1
notifications:
  email:
    on_success: never
install:
  - ./script/download_deps
  - go get -v github.com/mattn/goveralls
script:
  - ./script/testcoverage
  - cat cover.prof
after_success:
  # goveralls associates test coverage with correct branch by (default) reading travis-ci envvars
  - goveralls -coverprofile=cover.prof -repotoken=$COVERALLS_TOKEN
